### ISSUE TITLE
Production Checklist

### ISSUE THREAD

**Issue by Aradon267** [magshimim-next/cv-next#79]
- [x] [Supabase's list](https://supabase.com/docs/guides/platform/going-into-prod)
- [x] Update Google Credentials authorized URIs and origins
- [x] Update every localhost
- [x] Update Supabase's link accordingly(if needed)
- [x] Regenerate keys and secrets

Currently couldn't do [Redirect pino output to a file](https://betterstack.com/community/guides/logging/how-to-install-setup-and-use-pino-to-log-node-js-applications/#transporting-your-node-js-logs) and set logger level
